name: alumet-viz
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pyarrow  # Fast Parquet I/O for server-side caching of large DataFrames
  - python=3.12
  - pip:
    - dash
    - dash-ag-grid
    - dash-bootstrap-components
    - toml
