name: energy_measurement
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.12
  - seaborn
  - pip:
    - dash
    - dash-ag-grid
    - dash-bootstrap-components
    - marimo==0.18.0
    - toml
